### ISSUE TITLE
Invariant Violation: `metrics` should only be added once to the root level component. You have added to both App and App.

### ISSUE THREAD

**Issue by inside** [nfl/react-metrics#49]
Hi,

Here are some lines of my unit test code that generate an Invariant Violation:

```
// src/app.js
@metrics(metricsConfig, metricsOptions)
class App extends Component {
  ...
}

export default App
```

```
// src/app.spec.js
describe('App ', () => {
  it('should shallow render Hello', () => {
    const tree = shallow(<App children="Hello" />)
    expect(tree).toMatchSnapshot()
  })

  it('should shallow render World', () => {
    const tree = shallow(<App children="World" />)
    expect(tree).toMatchSnapshot()
  })
})
```

When I run the tests, I have this error:

```
Invariant Violation: `metrics` should only be added once to the root level component. You have added to both App and App.

  at invariant (node_modules/fbjs/lib/invariant.js:44:15)
  at MetricsContainer.componentWillMount (node_modules/react-metrics/lib/react/metrics.js:94:49)
  at node_modules/react-test-renderer/lib/shallow/ReactCompositeComponent.js:348:23
  at measureLifeCyclePerf (node_modules/react-test-renderer/lib/shallow/ReactCompositeComponent.js:75:12)
  at ShallowComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/shallow/ReactCompositeComponent.js:347:9)
  at ShallowComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/shallow/ReactCompositeComponent.js:258:21)
  at Object.mountComponent (node_modules/react-test-renderer/lib/shallow/ReactReconciler.js:46:35)
  at ReactShallowRenderer._render (node_modules/react-test-renderer/lib/shallow/ReactShallowRenderer.js:138:23)
  at _batchedRender (node_modules/react-test-renderer/lib/shallow/ReactShallowRenderer.js:85:12)
  at Object.batchedUpdates (node_modules/react-test-renderer/lib/shallow/ReactDefaultBatchingStrategy.js:60:14)
  at Object.batchedUpdates (node_modules/react-test-renderer/lib/shallow/ReactUpdates.js:97:27)
  at ReactShallowRenderer.render (node_modules/react-test-renderer/lib/shallow/ReactShallowRenderer.js:112:18)
  at ReactShallowRenderer.render (node_modules/enzyme/build/react-compat.js:180:39)
  at node_modules/enzyme/build/ShallowWrapper.js:128:26
  at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/shallow/Transaction.js:140:20)
  at Object.batchedUpdates (node_modules/react-test-renderer/lib/shallow/ReactDefaultBatchingStrategy.js:62:26)
  at Object.batchedUpdates (node_modules/react-test-renderer/lib/shallow/ReactUpdates.js:97:27)
  at ReactShallowRenderer.unstable_batchedUpdates (node_modules/react-test-renderer/lib/shallow/ReactShallowRenderer.js:130:25)
  at performBatchedUpdates (node_modules/enzyme/build/ShallowWrapper.js:103:21)
  at node_modules/enzyme/build/ShallowWrapper.js:127:9
  at withSetStateAllowed (node_modules/enzyme/build/Utils.js:284:3)
  at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:126:38)
  at shallow (node_modules/enzyme/build/shallow.js:19:10)
  at shallow (jest/__mocks__/enzyme.js:133:30)
  at Object.<anonymous> (src/__tests__/App.spec.js:22:36)
  at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
  at process._tickCallback (internal/process/next_tick.js:109:7)
```

This is because the variable `mountedInstances` is never reset.
I believe this variable is encapsulated in a closure and is not garbage collected.

What solutions do we have to test this main app component?

Thank you for your help

**Comment by inside** [comment]
Here's a repo for a reproducible use case:
https://github.com/inside/react-metrics-invariant

**Comment by Inoir** [comment]
Any updates on this? Or a workaround? Runnin in same issue

**Comment by potench** [comment]
http://airbnb.io/enzyme/docs/api/ShallowWrapper/unmount.html
Check the enzyme docs, you can re-architect your tests to the following:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import renderer from 'react-test-renderer';
import { shallow } from 'enzyme';
import toJson from 'enzyme-to-json';

describe("all tests", () => {
    let wrapper;

    beforeEach(() => {
        wrapper = shallow(<App />);
    });

    afterEach(() => {
        wrapper.unmount();
    });

    it('renders the snapshot without crashing 1', () => {
      expect(toJson(wrapper)).toMatchSnapshot();
    });

    it('renders the snapshot without crashing 2', () => {
      expect(toJson(wrapper)).toMatchSnapshot();
    });
});

```

**Comment by potench** [comment]
`react-metrics` is letting you know that you have multiple root Apps instantiated. You need to `mount` and `unmount` Apps in order to tear down `react-metrics` with it. Going to close this issue, feel free to open again if I've missed some nuance of your test design.
